import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope, faFloppyDisk, faPlus, faTrash } from '@fortawesome/free-solid-svg-icons'
import { Button, Col, Container, Form, FormControl, FormGroup, Image, ListGroup, ListGroupItem, Nav, Navbar, NavbarBrand, Row } from 'react-bootstrap'
import { useEffect, useState } from 'react'


export default function Home() {
  const apiUrl = process.env.apiUrl;
  const [notes, setNotes] = useState([]);
  const [selected, setSelected] = useState(null);

  useEffect(() => {
    fetch(apiUrl)
      .then(res => res.json())
      .then(data => setNotes(data));
  }, []);


  const addNewNote = () => {
    fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        title: "New Note",
        content: ""
      })
    })
      .then(res => res.json())
      .then(data => {
        setNotes([...notes, data]);
        setSelected({ ...data });
      });
  };

  const deleteNote = () => {
    fetch(`${apiUrl}/${selected.id}`, {
      method: "DELETE"
    })
      .then(res => {
        if (res.ok) {
          setNotes(notes.filter(note => note.id != selected.id));
          setSelected(null);
        }
      });
  };

  const saveNote = (e) => {
    e.preventDefault();
    fetch(`${apiUrl}/${selected.id}`, {
      method: "PUT",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(selected)
    })
      .then(res => {
        if (res.ok) {
          setNotes(notes.map(note => note.id == selected.id ? { ...selected } : note));
        }
      });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='image/png' href="/logo.png" />
      </Head>
      <main >
        <Navbar bg="dark" variant="dark">
          <Container>
            <NavbarBrand >
              <Image src='/logo.png' alt="Logo" width={30} height={30} className='d-inline-block align-top' />{" "}
              KeepNote
            </NavbarBrand>
          </Container>
        </Navbar>
        <Container className='mt-4'>
          <Row>
            <Col sm="4" lg="3">
              <Button variant='primary' className='w-100' onClick={addNewNote}>
                <FontAwesomeIcon icon={faPlus} /> New Note
              </Button>
              <ListGroup className='mt-4'>
                {notes.map(note => (
                  <ListGroupItem key={note.id} action onClick={() => setSelected({ ...note })} active={note.id == selected?.id}>
                    {note.title}
                  </ListGroupItem>
                ))}
              </ListGroup>
            </Col>
            <Col sm="8" lg="9">
              {selected &&
                <Form onSubmit={saveNote}>
                  <FormGroup className='mb-2'>
                    <FormControl type="text" placeholder='Enter title' value={selected.title} onChange={(e) => setSelected({ ...selected, title: e.target.value })} required />
                  </FormGroup>
                  <FormGroup className='mb-2'>
                    <FormControl type="text" as="textarea" rows={12} placeholder='Write something..' value={selected.content ?? ""} onChange={(e) => setSelected({ ...selected, content: e.target.value })} />
                  </FormGroup>
                  <div>
                    <Button variant='primary' className='me-2' type="submit">
                      <FontAwesomeIcon icon={faFloppyDisk} />{" "}Save
                    </Button>
                    <Button variant='danger' onClick={deleteNote} >
                      <FontAwesomeIcon icon={faTrash} />{" "}Delete
                    </Button>
                  </div>
                </Form>
              }
            </Col>
          </Row>
        </Container>
      </main>
    </>
  )
}
